const ORIGIN='https://omaryusuf.se';
export const FROM='Omar Yusuf <hej@hej.omaryusuf.se>';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function shell(content,preheader) {
  return `<!DOCTYPE html><html lang="sv"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Ett brev från Omar Yusuf</title></head><body style="margin:0;padding:0;background-color:#fff0b3;color:#20261e;font-family:Arial,Helvetica,sans-serif;"><span style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#fff0b3;">${escape(preheader)}</span><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" bgcolor="#fff0b3"><tr><td align="center" style="padding-top:32px;padding-right:16px;padding-bottom:32px;padding-left:16px;"><!--[if mso]><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600"><tr><td><![endif]--><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:600px;"><tr><td style="padding-bottom:25px;font-size:22px;line-height:28px;font-weight:bold;color:#20261e;">omar yusuf<span style="color:#234ce7;">.</span></td></tr>${content}<tr><td style="padding-top:24px;font-size:11px;line-height:18px;color:#525a45;">Lite hjärna. Lite hjärta. Lite bus i systemet.<br><a href="${ORIGIN}/integritet/" style="color:#20261e;">Integritet</a> · <a href="${ORIGIN}/" style="color:#20261e;">omaryusuf.se</a></td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
}
export function acknowledgment() {
  const html=shell(`<tr><td bgcolor="#234ce7" style="background-color:#234ce7;border-top-left-radius:15px;border-top-right-radius:15px;padding-top:28px;padding-right:28px;padding-bottom:22px;padding-left:28px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td valign="middle" style="color:#fffdf6;font-family:Arial,Helvetica,sans-serif;"><p style="margin-top:0;margin-bottom:14px;font-size:10px;line-height:16px;letter-spacing:1px;color:#fffdf6;">GLÄDJEVERKET / POSTAVDELNINGEN</p><h1 style="margin-top:0;margin-bottom:0;font-size:38px;line-height:39px;letter-spacing:-1px;color:#fffdf6;">Det kom<br>ett litet hej.</h1></td><td width="98" valign="middle"><img src="${ORIGIN}/mail/omar-smile.gif" alt="En gul figur som ler tillbaka" width="96" height="96" border="0" style="display:block;width:96px;height:96px;"></td></tr></table></td></tr><tr><td bgcolor="#fffdf6" style="background-color:#fffdf6;padding-top:32px;padding-right:28px;padding-bottom:30px;padding-left:28px;border-bottom-left-radius:15px;border-bottom-right-radius:15px;"><p style="margin-top:0;margin-bottom:12px;font-size:10px;line-height:16px;letter-spacing:1px;color:#525a45;">ETT LITET MOTTAGNINGSKVITTO</p><h2 style="margin-top:0;margin-bottom:22px;font-size:30px;line-height:33px;letter-spacing:-1px;color:#20261e;">Och det är framme.</h2><p style="margin-top:0;margin-bottom:17px;font-size:16px;line-height:26px;color:#20261e;">Tack för att du skrev. Jag har fått dina uppgifter och återkommer till dig.</p><p style="margin-top:0;margin-bottom:26px;font-size:16px;line-height:26px;color:#20261e;">Det här kvittot kom från maskinen.<br>Nästa svar kommer från människan.</p><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="border-top:1px dashed #9ca38a;padding-top:16px;font-size:12px;line-height:20px;color:#525a45;">Att betala</td><td align="right" style="border-top:1px dashed #9ca38a;padding-top:16px;font-size:12px;line-height:20px;font-weight:bold;color:#20261e;">Ett litet leende.</td></tr></table><p style="margin-top:28px;margin-bottom:28px;font-size:22px;line-height:28px;color:#234ce7;">/ Omar</p><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td bgcolor="#ffda44" style="background-color:#ffda44;border:1px solid #20261e;border-radius:7px;"><a href="${ORIGIN}/verkstad/" style="display:inline-block;padding-top:14px;padding-right:20px;padding-bottom:14px;padding-left:20px;font-size:13px;line-height:20px;font-weight:bold;text-decoration:none;color:#20261e;">Ta en liten omväg till verkstaden →</a></td></tr></table><p style="margin-top:20px;margin-bottom:0;font-size:11px;line-height:19px;color:#525a45;">Kvittot tar inte emot svar. Något mer på hjärtat? <a href="${ORIGIN}/kontakt/" style="color:#20261e;">Postluckan finns kvar.</a></p></td></tr>`, 'Dina uppgifter är framme hos Omar. Här är ditt lilla kvitto.');
  return {subject:'Ditt hej är framme. / Omar',html,text:'Tack för att du skrev. Jag har fått dina uppgifter och återkommer till dig.\n\nDet här kvittot kom från maskinen. Nästa svar kommer från människan.\n\n/ Omar\n\nEn liten paus: https://omaryusuf.se/verkstad/\nKvittot tar inte emot svar. Lägg till något via https://omaryusuf.se/kontakt/\nIntegritet: https://omaryusuf.se/integritet/'};
}
export function notification({name,email,message}) {
  const html=shell(`<tr><td bgcolor="#dfeac8" style="background-color:#dfeac8;padding-top:28px;padding-right:28px;padding-bottom:28px;padding-left:28px;border-top-left-radius:15px;border-top-right-radius:15px;"><p style="margin-top:0;margin-bottom:14px;font-size:10px;line-height:16px;letter-spacing:1px;color:#525a45;">POSTLUCKAN / NYTT MEDDELANDE</p><h1 style="margin-top:0;margin-bottom:0;font-size:34px;line-height:37px;color:#20261e;">Någon har knackat på.</h1></td></tr><tr><td bgcolor="#fffdf6" style="background-color:#fffdf6;padding-top:28px;padding-right:28px;padding-bottom:30px;padding-left:28px;border-bottom-left-radius:15px;border-bottom-right-radius:15px;"><p style="margin-top:0;margin-bottom:8px;font-size:11px;line-height:17px;color:#525a45;">FRÅN</p><p style="margin-top:0;margin-bottom:8px;font-size:23px;line-height:29px;font-weight:bold;color:#20261e;word-break:break-word;">${escape(name)}</p><p style="margin-top:0;margin-bottom:24px;font-size:15px;line-height:24px;color:#234ce7;word-break:break-all;">${escape(email)}</p><p style="margin-top:0;margin-bottom:12px;font-size:11px;line-height:17px;color:#525a45;">MEDDELANDE</p><p style="margin-top:0;margin-bottom:26px;font-size:16px;line-height:27px;color:#20261e;white-space:pre-wrap;overflow-wrap:anywhere;">${escape(message||'Inget meddelande. Bara en öppen dörr till ett samtal.')}</p><p style="margin-top:0;margin-bottom:0;border-top:1px dashed #9ca38a;padding-top:18px;font-size:12px;line-height:20px;color:#525a45;">Svara på det här mejlet för att skriva direkt till personen.</p></td></tr>`, 'Nya kontaktuppgifter från omaryusuf.se.');
  return {subject:'Ny post via omaryusuf.se',html,text:`Ny post via omaryusuf.se\n\nNamn: ${name}\nMejl: ${email}\n\n${message||'Inget meddelande lämnades.'}\n\nSvara på det här mejlet för att kontakta personen.`};
}
