import { icon, flower, breadcrumb } from './components.mjs';

export function humanSketch() {
  return `<svg class="curiosity-drawing" viewBox="0 0 290 210" aria-hidden="true"><g fill="none" stroke="#20261e" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M24 180h247M47 181l-5 17m210-17 5 17"/><g transform="rotate(6 130 118)"><rect x="47" y="60" width="169" height="111" rx="9" fill="#234ce7"/><rect x="57" y="71" width="148" height="86" rx="4" fill="#fff0b3"/><path d="m47 171-16 10h195l-10-10" fill="#a6b8ee"/><path d="m88 103-16 13 16 13m49-28-12 32m45-30 16 13-16 13" stroke="#234ce7" stroke-width="6"/></g><path d="M220 143h31v31q-16 8-31 0z" fill="#ff815f"/><path d="M251 149h8q12 12-8 16M230 133c-8-10 9-10 1-19m13 19c-8-10 9-10 1-19"/><path d="m228 52 12-13m-35 6 1-20m37 44 18-3" stroke="#234ce7" stroke-width="3"/><g transform="translate(66 30) rotate(-22)"><path d="M0 0q-7-13-16-8l8 8-8 8Q-3 14 2 5l24 20 7-8z" fill="#d8e6bf"/></g><circle cx="30" cy="118" r="7" fill="#ffda44"/><path d="m23 132-6 12m12-6-5 12"/><path d="m174 32 10-7 11 10-10 7z" fill="#ff815f"/></g></svg>`;
}

export function projectAdditions() {
  return `<article class="project"><a href="/projekt/blade-blend/" class="project-art blade-art" aria-label="Utforska Blade & Blend Studio"><div class="art-topline"><span>BLADE & BLEND / GÖTEBORG</span>${icon('diagonal')}</div><div class="barber-pole" aria-hidden="true"><i></i><b></b></div><span class="blade-art-word" aria-hidden="true">En vassare<br>vardag.</span><span class="art-caption">FRÅN BOKNING TILL NYKLIPPT.</span></a><div class="project-description"><div><p class="eyebrow">FULLSTACK · BOKNING · SOLOUTVECKLAT</p><h3><a href="/projekt/blade-blend/">Blade & Blend ${icon('diagonal')}</a></h3></div><p>En hel webbplats till en barbershop i Göteborg. Från första intrycket till bokningen bakom kulisserna.</p></div></article>
  <article class="project"><a href="/projekt/backhaul/" class="project-art backhaul-art" aria-label="Utforska Backhaul Intelligence Engine"><div class="art-topline"><span>SSEN HACKATHON / EINRIDE TRACK</span>${icon('diagonal')}</div><svg viewBox="0 0 420 180" class="route-art" aria-hidden="true"><path d="M20 150C90 150 45 40 145 55S260 170 310 65 370 25 400 35" stroke="#fff0b3" stroke-width="3" stroke-dasharray="7 8" fill="none"/><circle cx="20" cy="150" r="9" fill="#ff815f"/><circle cx="400" cy="35" r="9" fill="#ffda44"/><g transform="translate(156 67) rotate(22)"><rect width="100" height="42" rx="5" fill="#d8e6bf"/><path d="M100 12h23l12 16v14h-35z" fill="#ffda44"/><circle cx="24" cy="46" r="10" fill="#20261e"/><circle cx="112" cy="46" r="10" fill="#20261e"/><path d="M14 15h45m-45 10h31" stroke="#20261e" stroke-width="3"/></g></svg><span class="backhaul-word" aria-hidden="true">Hemväg.<br>Inte tomväg.</span><span class="art-caption">EN IDÉ FÖR DEN TOMMA RETURRESAN.</span></a><div class="project-description"><div><p class="eyebrow">HACKATHON · AI · LOGISTIK</p><h3><a href="/projekt/backhaul/">Backhaul ${icon('diagonal')}</a></h3></div><p>Vårt hackathonbidrag letar efter möjliga returlaster. För lastbilar ska helst ha mer med sig hem än chauffören.</p></div></article>`;
}

const projects = {
  blade: { kicker:'BLADE & BLEND STUDIO / SOLOUTVECKLAT', heading:'En bra klippning.<br><span>En enklare bokning.</span>', lead:'En fullstack-webbplats till en barbershop i Göteborg. Jag byggde hela lösningen själv, från gränssnitt till bokningsflöde.', meta:['Roll: soloutvecklare','Plats: Göteborg','Fullstack'], title:'Mer än en snygg framsida.', paragraphs:[
    'En barbershops webbplats behöver både ge rätt första intryck och göra det lätt att boka. Blade & Blend har svenska och engelska, ett responsivt gränssnitt och onlinebokning.',
    'Bakom sidan finns tjänster och personal, bokningshantering, en administrativ vy och transaktionsmejl. Frontend är byggd med Preact och TypeScript, backend med Supabase och driften med Cloudflare Workers.',
    'Jag arbetade med både det besökaren ser och det som behöver fungera efter ett knapptryck: validering, åtkomstkontroll och kopplingen mellan webbplats, databas och mejl.'
  ], link:'https://bladeblendstudio.se', label:'Besök Blade & Blend', aside:'En bra bokning ska kännas enkel.<br>Även när koden bakom inte är det.' },
  backhaul: { kicker:'SSEN NATIONAL HACKATHON / EINRIDE TRACK 2026', heading:'Full last dit.<br><span>En idé för hemvägen.</span>', lead:'Jag deltog i SSEN National Hackathon, Einride Track 2026, med Backhaul Intelligence Engine. Ett lagbidrag om att hitta möjliga laster för tomma returresor.', meta:['Hackathonbidrag','Prototyp','AI + logistik'], title:'En tom returresa är en fråga.', paragraphs:[
    'Projektet tar en transportkorridor mellan Stockholm och Göteborg, söker efter företag längs rutten och rangordnar dem som möjliga kunder för returlaster.',
    'Prototypen kombinerar geografisk filtrering, företagsdata, poängsättning och förslag på kontaktmejl. Gränssnittet byggdes med Next.js och backend med Python och FastAPI.',
    'Det här var ett hackathonbidrag, inte ett produktionssystem hos Einride. Demonstrationen använde både förberedd och syntetisk data. Vi vann inte, men idén och lärdomarna följde med hem.'
  ], link:null, label:null, aside:'Lastbilen skulle ändå tillbaka.<br>Det var där idén började.' }
};
export function projectDetail(page) {
  const p = projects[page.template];
  return `<div class="section-wrap">${breadcrumb(page)}<section class="project-hero"><div><p class="eyebrow">${p.kicker}</p><h1>${p.heading}</h1><p class="large-lead">${p.lead}</p></div>${flower('project-detail-flower')}</section><div class="interest-tags project-meta">${p.meta.map(x=>`<span>${x}</span>`).join('')}</div><section class="about-body"><aside class="about-side"><p>${p.aside}</p></aside><div><h2>${p.title}</h2>${p.paragraphs.map(x=>`<p>${x}</p>`).join('')}${p.link ? `<a class="button button-ink" href="${p.link}">${p.label} ${icon('diagonal')}</a>` : ''}</div></section><section class="project-outro"><h2>Nästa idé börjar<br>med en fråga.</h2><a class="text-link" href="/#byggen">Fler byggen ${icon('arrow')}</a></section></div>`;
}

export function experience() {
  return `<section class="experience-section" aria-labelledby="experience-title"><p class="eyebrow">DET FINNS LITE BAKGRUND OCKSÅ</p><h2 id="experience-title">Några saker<br>i verktygslådan.</h2><div class="experience-grid"><article><span class="experience-label">UTBILDNING / PÅGÅENDE</span><h3>Chalmers.</h3><p>Jag läser till civilingenjör med inriktning Automation and Mechatronics, med masterinriktningen M.Sc. Systems, Learning and Control.</p><p>Jag har sedan tidigare en avslutad B.Sc. som maskiningenjör.</p></article><article><span class="experience-label">ERFARENHET / DELTID</span><h3>AI, på nära håll.</h3><p>Jag har arbetat deltid med AI-dataannotering hos Rebl Industries genom bemanningsföretaget Chalmers Teknologbolag.</p></article><article><span class="experience-label">ÖPPEN KÄLLKOD</span><h3>Små ändringar.<br>Gemensamma verktyg.</h3><p>Jag bidrar också till andras projekt. Här är några av mina sammanslagna ändringar.</p><div class="contribution-links"><a href="https://github.com/astral-sh/ruff/pull/26419">Ruff ${icon('diagonal')}</a><a href="https://github.com/payloadcms/payload/pull/16120">Payload ${icon('diagonal')}</a><a href="https://github.com/ccusage/ccusage/pull/889">ccusage ${icon('diagonal')}</a></div></article><article><span class="experience-label">SSEN NATIONAL HACKATHON / 2026</span><h3>En idé.<br>En intensiv helg.</h3><p>Jag deltog i Einride Track med Backhaul Intelligence Engine. Ett lagprojekt om smartare returtransporter.</p><a class="text-link" href="/projekt/backhaul/">Se hackathonbidraget ${icon('arrow')}</a></article></div></section>`;
}

export function postalForm() {
  return `<details class="postbox" data-postbox><summary class="envelope"><span class="envelope-top"><span class="eyebrow">DIREKT TILL OMAR</span><span class="postage" aria-hidden="true">${flower()}<span>INGET PORTO</span></span></span><span class="envelope-line">Inga frimärken<br>behövs.</span><span class="envelope-cta"><span class="envelope-open">Öppna kuvertet</span><span class="envelope-close">Stäng kuvertet</span> ${icon('arrow')}</span><span class="envelope-seam" aria-hidden="true"></span></summary>
    <div class="letter-paper"><form data-contact-form novalidate><div class="letter-fields"><div><label for="contact-name">Ditt namn <span>(obligatoriskt)</span></label><input id="contact-name" name="name" autocomplete="name" required maxlength="100"><label for="contact-email">Din mejladress <span>(obligatoriskt)</span></label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"></div><div><label for="contact-message">Några rader <span>(om du vill)</span></label><textarea id="contact-message" name="message" rows="5" maxlength="4000"></textarea></div></div><div class="contact-trap" aria-hidden="true"><label for="contact-website">Lämna tomt</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div><div data-turnstile class="security-widget"></div><p class="form-feedback" data-contact-status role="status" aria-live="polite"></p><div class="letter-actions"><button class="button button-ink" type="submit" data-contact-send disabled>Skicka till Omar ${icon('arrow')}</button><a href="/integritet/#kontakt">Så hanteras dina uppgifter</a></div></form><section data-contact-success class="letter-success" hidden tabindex="-1"><span class="arrival-stamp" aria-hidden="true">FRAMME!</span>${flower()}<h2>Posten kom fram.</h2><p>Jag återkommer till mejladressen du skrev.<br>Ett litet kvitto är också på väg dit.</p><span class="letter-signature">/ Omar</span></section><noscript><p>Formuläret behöver JavaScript. Du hittar mig också via GitHub-länkarna nedan.</p></noscript></div></details>`;
}

export function extraGames() {
  return `<section class="memory-section game-section" aria-labelledby="memory-title"><div class="section-wrap game-inner"><div class="game-copy"><span class="round-number">03</span><p class="eyebrow">AVDELNINGEN FÖR BEKANTA ANSIKTEN</p><h2 id="memory-title">Har vi inte<br>setts förut?</h2><p>Tolv kort. Sex par. Ditt korttidsminne<br>har blivit kallat till ett väldigt litet möte.</p><p class="game-status" data-memory-status role="status" aria-live="polite">Vänd två kort och se om de känner varandra.</p><button class="button button-outline js-only" hidden data-memory-reset>Blanda om ${icon('arrow')}</button></div><div class="memory-board"><div class="memory-grid" data-memory-grid></div><span class="game-board-caption">INGEN BETYGSSÄTTNING AV HJÄRNAN PÅGÅR.</span><noscript><p>Aktivera JavaScript för att spela memory.</p></noscript></div></div></section>
  <section class="fika-section game-section" aria-labelledby="fika-title"><div class="section-wrap game-inner"><div class="game-copy"><span class="round-number">04</span><p class="eyebrow">AVDELNINGEN FÖR UNGEFÄRLIG TID</p><h2 id="fika-title">Fem sekunder.<br>På en höft.</h2><p>Starta. Känn efter. Stoppa när du tror att fem sekunder gått. Inga klockor att tjuvkika på.</p><p class="game-status" data-fika-status role="status" aria-live="polite">Din inre äggklocka får göra ett försök.</p><button class="button button-ink js-only" hidden data-fika-button>Starta min fika ${icon('play')}</button></div><div class="fika-board"><span class="eyebrow">FIKALABBET / 05 S</span><div class="coffee-scene" aria-hidden="true"><div class="coffee-steam"><i></i><i></i><i></i></div><div class="coffee-handle"></div><div class="coffee-cup"><span>ta det<br><strong>lite lagom.</strong></span><i></i><i></i><b></b></div><div class="coffee-saucer"></div></div><output class="fika-readout" data-fika-result aria-label="Din uppmätta tid">? , ??</output><span class="game-board-caption">TIDEN GÅR. KOPPEN STANNAR.</span><noscript><p>Aktivera JavaScript för att testa tidskänslan.</p></noscript></div></div></section>`;
}
