import { humanSketch, projectAdditions } from './expansion.mjs';
import { icon, flower, machine } from './components.mjs';
export function home() {
  return `<section class="hero section-wrap" aria-labelledby="hero-title">
  <div class="hero-copy"><p class="eyebrow hero-eyebrow"><span class="tiny-star" aria-hidden="true">✳</span> MASKININGENJÖR. OCH ANNAT NYFIKET.</p><h1 id="hero-title">Omar<br>Yusuf<span class="title-dot">.</span></h1><p class="hero-tagline">Teknik med hjärna.<br>Lite bus i systemet.</p><p class="hero-intro">Välkommen till min lilla del av internet. Här möts maskinteknik, kod och en orimlig omsorg om detaljer.</p><a href="#byggen" class="button button-ink">Scrolla ner för att se mina projekt ${icon('down')}</a><span class="hero-footnote">(eller så klickar du på den stora knappen, ditt val)</span></div>
  ${machine()}
  <div class="hero-bottom"><span><i class="status-dot"></i> VÄLKOMMEN IN I VERKSTADEN</span><span>Ta med nyfikenheten. Lämna slipsen.</span><span class="scroll-note">DET FINNS MER NEDAN ${icon('down')}</span></div></section>
  <div class="good-strip" aria-label="Sidans anda"><span>Seriöst nyfiken.</span>${flower()}<span>Oseriöst glad.</span>${flower()}<span>Alltid människa.</span>${flower()}<span class="strip-extra">Aldrig riktigt färdigtänkt.</span></div>
  <section class="work-section section-wrap" id="byggen" aria-labelledby="work-title"><div class="section-heading"><div><p class="eyebrow">01 / FRÅN VERKSTADEN</p><h2 id="work-title">Bra saker börjar<br>med <span class="scribble-underline">”tänk om”.</span></h2></div><p>Något användbart. Något lekfullt.<br>Helst lite av båda.</p></div>
  <div class="project-grid"><article class="project project-furl"><a href="/projekt/furl/" class="project-art furl-art" aria-label="Utforska projektet Furl"><div class="art-topline"><span>FURL / ÖPPEN KÄLLKOD</span>${icon('diagonal')}</div><div class="furl-folds" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><span class="furl-art-word" aria-hidden="true">less, but<br>all there.</span><span class="art-caption">STORT SAMMANHANG. MINDRE BRUS.</span></a><div class="project-description"><div><p class="eyebrow">AI-VERKTYG · PYTHON · MCP</p><h3><a href="/projekt/furl/">Furl ${icon('diagonal')}</a></h3></div><p>Ett verktyg som packar ihop AI-agenters stora verktygssvar. Originalet finns kvar att hämta.</p></div></article>
  <article class="project project-joy"><a href="/verkstad/" class="project-art joy-art" aria-label="Öppna glädjeverkstaden"><div class="art-topline"><span>ETT LITET INTERNETEXPERIMENT</span>${icon('diagonal')}</div><div class="joy-art-face" aria-hidden="true"><span class="joy-art-eyes"><i></i><i></i></span><span class="joy-art-mouth"></span></div><span class="joy-art-sticker" aria-hidden="true">FÅR<br>TRYCKAS<br>PÅ!</span><span class="art-caption">INGEN NYTTA BEHÖVER REDOVISAS.</span></a><div class="project-description"><div><p class="eyebrow">LEK · SMÅ VINSTER · BUBBLOR</p><h3><a href="/verkstad/">Glädjeverkstaden ${icon('diagonal')}</a></h3></div><p>En liten maskin, några bubblor och en fullt rimlig anledning att göra något orimligt.</p></div></article>${projectAdditions()}</div>
  <a class="text-link all-work" href="https://github.com/omar-y-abdi" rel="me">Mer kod och nyfikenhet på GitHub ${icon('diagonal')}</a></section>
  <section class="about-teaser" aria-labelledby="about-teaser-title"><div class="section-wrap about-teaser-inner"><div class="human-art" aria-hidden="true"><div class="human-card"><span class="id-card-top">EN MÄNNISKA, INTE EN MALL.</span>${humanSketch()}<span class="id-name">OMAR YUSUF</span><div class="id-card-bottom"><span>DRIVMEDEL: NYFIKENHET</span>${icon('smile')}</div></div><div class="human-sticker">Lite mer<br><strong>varför inte?</strong></div>${flower('human-flower')}</div><div class="about-teaser-copy"><p class="eyebrow">02 / MÄNNISKAN BAKOM KNAPPEN</p><h2 id="about-teaser-title">En ingenjör.<br>Inte en robot<span>.</span></h2><p>Jag gillar när saker fungerar. Men också när de känns. För mig får bra teknik gärna ha lite personlighet.</p><p>Maskinteknik, kod och ett och annat ”jag ska bara testa en sak till”. Det är ungefär där du hittar mig.</p><a href="/om/" class="button button-outline">Lite mer om mig ${icon('arrow')}</a></div></div></section>
  <section class="contact-band section-wrap" aria-labelledby="contact-title"><div><p class="eyebrow">03 / SAKER BÖRJAR MED ETT HEJ</p><h2 id="contact-title">En bra idé?<br>Ett dåligt skämt?</h2><p>Båda är fullt giltiga skäl att höra av sig.</p></div><a href="/kontakt/" class="contact-circle">Säg hej ${icon('diagonal')}</a><span class="contact-note" aria-hidden="true">Låg tröskel.<br>Hög nyfikenhet.</span></section>`;
}
