import { site } from '../content/site.mjs';
import { breadcrumb, icon } from './components.mjs';
const pages = {
  privacy: {
    eyebrow: 'LITE DATA. MYCKET RESPEKT.', heading: 'Din integritet<br>är inte en produkt.', lead: 'Här ska du kunna vara nyfiken utan att bli en besökarprofil.',
    sections: [
      ['Vem står bakom sidan?', `<p>Webbplatsen omaryusuf.se är Omar Yusufs personliga webbplats. Frågor om webbplatsen eller personuppgifter kan tas via kontaktvägarna på <a href="/kontakt/">kontaktsidan</a>. Publicera inte känsliga uppgifter i offentliga GitHub-ärenden.</p>`],
      ['Vad sidan samlar in', '<p>Det finns inga konton, nyhetsbrev, annonser eller inbäddade sociala flöden. Glädjeverkstaden körs i din webbläsare. Ett kort som sparas som bild skapas på din egen enhet. En delad kortlänk innehåller bara ett ID för ett förskrivet kort, inte ett personligt meddelande.</p>'],
      ['Kontaktformuläret', '<p id="kontakt">När du använder postluckan lämnar du namn och mejladress. Ett meddelande är valfritt. Uppgifterna används för att ta emot och besvara din kontakt. De läggs inte till i någon prenumeration och skickas inte till statistikfunktionen.</p><p>Omar Yusuf ansvarar för kontaktuppgifterna. Ändamålet är att hantera den kontakt som du själv tar initiativ till, med stöd av det berättigade intresset att kunna besvara förfrågningar. Lämna inte känsliga personuppgifter i formuläret.</p><p>Uppgifterna skickas via webbplatsens Cloudflare Worker till Resend, som förmedlar ett mejl till Omar och ett separat mottagningskvitto till dig. Omars privata mottagaradress lämnas inte ut i sidans kod eller i ditt kvitto. Inga formulärvärden sparas i kakor, localStorage eller webbplatsens databas.</p><p>Kontaktmejl behöver finnas kvar under dialogen och eventuell uppföljning. Webbplatsen raderar inte automatiskt mejl hos mottagaren eller leverantören. Du kan använda <a href="/kontakt/">kontaktsidan</a> för frågor om dina uppgifter eller för att begära radering. Uppgifter ska inte behållas längre än vad kontaktens ändamål kräver.</p>'],
      ['Skydd mot spam', '<p>När du öppnar kuvertet laddas Cloudflare Turnstile, om kontaktfunktionen är aktiverad. Den behandlar tekniska uppgifter om webbläsaren och anslutningen för att skilja legitima förfrågningar från automatiserade angrepp. Formulärets namn, mejladress och meddelande skickas först när du väljer att skicka.</p><p>Servern kontrollerar säkerhetsbeviset, ursprung och anropets storlek. Hastighetsbegränsningen använder kryptografiskt härledda värden av IP-adress och mejladress, inte uppgifterna i klartext. De är inte besökarprofiler eller anonyma uppgifter. Ett inskicknings-ID skyddar mot dubbla utskick vid omförsök. Resend behåller idempotensnyckeln i 24 timmar.</p><p>Säkerhetskontrollen är skild från frivillig statistik. Öppnings- och klickspårning i Resend ska vara avstängd. Hosting, spamkontroll och mejlleverans kan innebära att uppgifter behandlas utanför EU/EES enligt leverantörernas avtal och överföringsskydd. Läs <a href="https://www.cloudflare.com/privacypolicy/">Cloudflares integritetspolicy</a> och <a href="https://resend.com/legal/privacy-policy">Resends integritetspolicy</a>.</p>'],
      ['Frivillig statistik', '<p>När statistik är aktiverad och du har sagt ja kan sidan räkna sidvisningar och den första användningen av maskinen, en färdig bubbelomgång eller en projektlänk under en sidvisning. Varje händelsetyp räknas högst en gång tills sidan laddas på nytt. Bara fasta händelsenamn och kända sidvägar skickas till webbplatsens egen statistikadress.</p><p>Statistikfunktionen lagrar inte IP-adress, besökar-ID, namn, e-post, skärmstorlek, fullständiga länkar, sökparametrar eller hänvisande webbplats. Tidpunkten för en mottagen händelse registreras av Cloudflare Analytics Engine. Händelserna lagras där i tre månader. Det är enkel händelsestatistik, inte ett mått på unika människor.</p><p>Samtycke är grunden för den frivilliga statistiken. Inget sådant anrop görs innan ett ja. Du kan neka utan att förlora funktioner. Ett nej stoppar nya statistikförfrågningar, även om webbläsaren inte kan spara det nya valet. Då gäller pausen den öppna sidan och du får ett meddelande om det. Statistikfunktionen saknar ett besökar-ID. Det går därför inte att söka fram en viss persons händelser med ett sådant ID.</p>'],
      ['Kakor och inställningar', '<p>Sidan kan spara ditt dataval och ett uttryckligt val att pausa rörelser. Dessa inställningar används bara för att komma ihåg vad du bad om. Läs namn, innehåll och lagringstid på <a href="/kakor/">sidan om kakor</a>.</p>'],
      ['Hosting och tekniska uppgifter', '<p>Webbplatsen är avsedd att köras hos Cloudflare. För att leverera en webbplats och skydda den mot angrepp behöver hostingleverantören behandla tekniska nätverksuppgifter, exempelvis IP-adress. Det är skilt från den frivilliga statistikfunktionen. Webbplatsens kod sparar inga egna åtkomstloggar eller fullständiga förfrågningar.</p><p>Vilka säkerhetsloggar och avtalsvillkor som gäller hos Cloudflare måste kontrolleras i det anslutna hostingkontot vid publicering. Vi gör därför inget löfte om att all teknisk behandling är anonym eller enbart sker inom EU.</p>'],
      ['Dina möjligheter', '<p>Du kan ändra dataval i sidfoten, ta bort webbplatsens kakor i webbläsaren och välja att inte följa externa länkar. Sidan respekterar dessutom aktiverad Global Privacy Control eller Do Not Track genom att inte skicka frivillig statistik.</p><p>Vid behandling av personuppgifter kan du, beroende på omständigheterna, ha rätt till information, tillgång, rättelse, radering, begränsning, invändning och dataportabilitet. Du kan också klaga hos Integritetsskyddsmyndigheten, IMY. Rättigheterna gäller inte utan undantag och den här statistikfunktionen saknar ett besökar-ID att använda för att hitta en viss persons händelser.</p>'],
    ],
  },
  cookies: {
    eyebrow: 'SMÅ KAKOR. INGEN SMYGFEST.', heading: 'Du bestämmer<br>vad som sparas.', lead: 'Det går alldeles utmärkt att säga nej. Maskinen blir inte sur.',
    sections: [
      ['Vad en kaka gör här', '<p>En kaka är en liten inställning som sparas i webbläsaren. På den här sidan används den för att minnas dina uttryckliga val, inte för reklam eller för att känna igen dig mellan andra webbplatser.</p>'],
      ['Kakorna som webbplatsen själv sätter', '<div class="table-scroll"><table><caption>Förstapartskakor på omaryusuf.se</caption><thead><tr><th scope="col">Namn</th><th scope="col">Innehåll och syfte</th><th scope="col">Lagringstid</th></tr></thead><tbody><tr><th scope="row">oy_privacy</th><td>Version och ditt val: tillåt eller neka statistik. Sätts först när du gör ett val. Ingen personlig identifierare.</td><td>180 dagar</td></tr><tr><th scope="row">oy_motion</th><td>Ditt uttryckliga val att pausa rörelser. Sätts först när du ändrar rörelseinställningen.</td><td>180 dagar</td></tr></tbody></table></div><p>Kakorna behövs för att komma ihåg de inställningar du begär. De använder sökvägen / och SameSite=Lax. På den publicerade HTTPS-webbplatsen har de också Secure. Ingen av dem används för annonsering eller för att ge dig ett unikt besökar-ID.</p>'],
      ['Statistik kräver ditt ja', '<p>Statistik är avstängd tills du har valt ”Tillåt statistik”, och skickas bara när statistikfunktionen är tillgänglig. Ett besök, scrollning eller stängning av en ruta räknas aldrig som ett ja.</p><p>Du kan välja ”Bara nödvändiga” lika lätt som att tillåta statistik. Statistik krävs inte för att läsa sidan, använda maskinen, dela ett kort eller poppa bubblor.</p><p>Om statistik inte är aktiverad i den aktuella installationen visas ingen samtyckesbanner för den. Datavalsrutan visar då att statistik inte är aktiv.</p>'],
      ['Ändra eller återkalla', '<p>Välj ”Ändra dataval” i sidfoten. Ett nej stoppar nya statistikförfrågningar direkt och försöker spara ditt val. Om webbläsaren inte tillåter det gäller pausen den öppna sidan. Ett meddelande ber dig kontrollera kakinställningarna innan du byter sida. Du behöver inte ladda om sidan. Du kan också ta bort kakorna i webbläsaren. Då kan du få frågan på nytt.</p><p>Om webbläsaren blockerar kakor hålls ditt val bara i minnet för den öppna sidan. En ny sida kan då fråga igen. Frivillig statistik skickas inte om ett tillåtande val inte kunnat sparas. Global Privacy Control och Do Not Track har alltid företräde framför ett tillåtande val.</p>'],
      ['Tredje parter', '<p>Sidan laddar inga externa typsnitt, analysbibliotek, videor, kartor eller sociala flöden. Kontaktformuläret laddar Cloudflare Turnstile när kuvertet öppnas. Det är ett skydd mot spam, inte frivillig statistik. Se <a href="/integritet/#kontakt">integritetspolicyn</a> för behandlingen i kontaktflödet. När du följer en extern länk gäller den webbplatsens egna villkor. Cloudflare kan vid publicering använda separata säkerhetsfunktioner. Sådana funktioner måste stämmas av mot denna policy i hostingkontot.</p>'],
    ],
  },
  terms: {
    eyebrow: 'LITEN SIDA. RAKA VILLKOR.', heading: 'Bra att veta.<br>Innan du trycker.', lead: 'Du är välkommen att läsa, utforska och ta en liten paus.',
    sections: [
      ['Vad webbplatsen är', '<p>omaryusuf.se är en personlig presentation av Omar Yusuf och utvalda projekt. Glädjeverkstaden är ett lekfullt webbexperiment. Den säljer inga tjänster, tar inte emot beställningar och erbjuder inga betalda abonnemang.</p>'],
      ['Glädjeverkstaden', '<p>Texter från maskinen är förskrivna skämt, vänliga uppmuntringar och små påminnelser. De är inte personligt anpassade råd, diagnoser eller professionell rådgivning. Du får gärna spara och dela de kort som du skapar i verkstaden.</p>'],
      ['Projekt och öppen källkod', '<p>Beskrivningarna här är översikter. Aktuell funktion, installation, licens och kända begränsningar för Furl finns i projektets GitHub-repo. Projektets egen licens gäller för dess kod och ersätts inte av dessa webbplatsvillkor. Illustrationer på denna sida är inte oberoende prestandamätningar.</p>'],
      ['Innehåll och externa länkar', '<p>Webbplatsens originaltexter och utformning tillhör Omar Yusuf om inget annat anges. Det särskilda tillståndet att dela verkstadens kort gäller även utan ett separat godkännande. Andra aktörers namn och kännetecken tillhör respektive rättighetshavare.</p><p>Externa länkar leder till webbplatser med egna villkor och egen behandling av uppgifter. Deras innehåll kan förändras. Lämna inte privata uppgifter i offentliga ärenden.</p>'],
      ['Tillgänglighet och förändringar', '<p>Innehåll och funktioner kan uppdateras. Ingen oavbruten tillgänglighet eller viss effekt på ditt humör utlovas. Sådana förbehåll begränsar inte rättigheter som följer av tvingande lag.</p><p>Kontakta Omar via <a href="/kontakt/">kontaktsidan</a> om du hittar ett problem eller har en fråga.</p>'],
    ],
  },
  accessibility: {
    eyebrow: 'ALLA SKA KUNNA TRYCKA PÅ KNAPPEN.', heading: 'Fler sätt<br>att vara med.', lead: 'Lekfullt ska inte betyda svåranvänt.',
    sections: [
      ['Tangentbord och tydliga kontroller', '<p>Länkar och knappar kan användas med tangentbord. Tab flyttar fokus, Enter följer länkar och Enter eller mellanslag aktiverar knappar. Radioknapparna i verkstaden kan också väljas med piltangenter. Det finns en ”Hoppa till innehållet”-länk när du börjar navigera med tangentbord.</p><p>Dialogrutan för dataval håller fokus tills den stängs och kan stängas med Escape. Glädjemaskinens resultat och bubbelräknaren har textmeddelanden för hjälpmedel. Att hovra, dra eller använda ljud är aldrig ett krav.</p>'],
      ['Mindre rörelse, samma innehåll', '<p>Webbplatsen följer webbläsarens eller operativsystemets inställning för minskad rörelse. Knappen i sidhuvudet kan också pausa rörelser. Då ersätts rörelse med omedelbara tillståndsbyten. Innehåll och funktion finns kvar.</p><p>Bubblornas ljud är avstängt från början och aktiveras bara när du själv väljer det. Ingen viktig information ges enbart med ljud, färg eller animation.</p>'],
      ['Läsbarhet och små skärmar', '<p>Sidan använder semantiska rubriker, tydliga knappnamn och synlig tangentbordsfokus. Text och kontroller är utformade med kontrast i åtanke. Innehållet anpassas för smala skärmar och textförstoring.</p><p>Dekorativa figurer är dolda för skärmläsare. Sidornas text och vanliga länkar fungerar utan JavaScript. De interaktiva leksakerna kräver JavaScript och beskriver detta när det är avstängt.</p>'],
      ['Vad vi inte lovar', '<p>Automatiska tester och visuell granskning är inte en fullständig tillgänglighetscertifiering. Alla kombinationer av webbläsare, skärmläsare, enheter och personliga hjälpmedel har inte provats. Detta är praktisk information om stödet, inte ett påstående om att inga hinder finns.</p>'],
      ['Rapportera ett hinder', '<p>Hör gärna av dig via <a href="/kontakt/">kontaktsidan</a>. Beskriv vilken sida du var på, vad du försökte göra och vilket hjälpmedel eller vilken webbläsare du använde. Dela inte känsliga uppgifter i ett offentligt GitHub-ärende.</p>'],
    ],
  },
};
export function legal(page) {
  const data = pages[page.template];
  return `<div class="section-wrap legal-wrap">${breadcrumb(page)}<header class="legal-heading"><p class="eyebrow">${data.eyebrow}</p><h1>${data.heading}</h1><p class="large-lead">${data.lead}</p><span class="updated">Senast uppdaterad ${site.updated}</span></header><div class="legal-content">${data.sections.map(([heading, body], i) => `<section aria-labelledby="legal-${i}"><h2 id="legal-${i}">${heading}</h2>${body}</section>`).join('')}<div class="legal-actions"><button class="button button-ink js-only" data-privacy-open hidden>Ändra dataval ${icon('arrow')}</button><a href="/" class="text-link">Tillbaka till startsidan ${icon('arrow')}</a></div></div></div>`;
}
