import { experience, extraGames, postalForm } from './expansion.mjs';
import { site } from '../content/site.mjs';
import { icon, flower, machine, breadcrumb } from './components.mjs';
export function workshop(page) {
  return `<div class="section-wrap">${breadcrumb(page)}<section class="workshop-intro"><p class="eyebrow">ETT LITET AVBROTT I DET VÄLDIGT VIKTIGA</p><h1>Välkommen till<br><span>glädjeverkstaden.</span></h1><p>Du behöver inte åstadkomma något här.<br>Men ett litet leende vore ju trevligt.</p></section><section class="workshop-machine-section" aria-labelledby="workshop-machine-title"><div class="workshop-instructions"><span class="round-number">01</span><h2 id="workshop-machine-title">En liten vinst.<br>Precis till dig.</h2><p>Välj vad du är sugen på. Tryck på knappen. Maskinen sköter resten.</p><fieldset class="flavor-options"><legend>Vad får det lov att vara?</legend><label><input type="radio" name="flavor" value="kind" checked><span>Lite pepp ${icon('smile')}</span></label><label><input type="radio" name="flavor" value="joke"><span>Torr humor <span aria-hidden="true">☀</span></span></label><label><input type="radio" name="flavor" value="pause"><span>En snäll påminnelse ${icon('pause')}</span></label><label><input type="radio" name="flavor" value="roast"><span>En kärleksfull gliring ${icon('smile')}</span></label></fieldset><div class="card-actions js-only" hidden><button class="button button-outline" data-share disabled>Kopiera kortlänk ${icon('copy')}</button><button class="text-link" data-save disabled>Spara som bild ${icon('download')}</button></div><div class="copy-fallback" data-copy-fallback hidden><label for="share-url">Kopiera länken själv</label><input id="share-url" readonly><p>Markera länken och kopiera den med tangentbordet.</p></div><p class="workshop-aside">Helt utan livscoach-abonnemang.</p></div>${machine({ workshop: true })}</section></div>
  <section class="bubble-section" aria-labelledby="bubble-title"><div class="section-wrap bubble-inner"><div class="bubble-copy"><span class="round-number">02</span><p class="eyebrow">AVDELNINGEN FÖR ONÖDIGT SKÖNA SAKER</p><h2 id="bubble-title">En helt<br>oproduktiv paus.</h2><p>Ingen topplista. Ingen tidtagning.<br>Bara bubblor som får poppas.</p><div class="bubble-progress" data-bubble-status role="status" aria-live="polite">12 bubblor. Gott om tid.</div><div class="bubble-controls js-only" hidden><button class="button button-outline" data-bubble-reset>En ny omgång ${icon('arrow')}</button><button class="sound-toggle" data-sound-toggle aria-pressed="false">${icon('sound')} Ljud: av</button></div></div><div class="bubble-board" aria-label="Bubbelpaus"><div class="bubble-grid">${Array.from({ length: 12 }, (_, i) => `<button class="bubble" data-bubble="${i}" aria-label="Poppa bubbla ${i + 1}" aria-pressed="false" disabled><span aria-hidden="true"></span></button>`).join('')}</div><span class="bubble-board-label">POPP / AVDELNINGEN FÖR SMÅ LEENDEN</span></div><noscript><p>Aktivera JavaScript för att poppa bubblorna. Det går lika bra att ta en vanlig paus.</p></noscript></div></section>
  ${extraGames()}<section class="small-outro section-wrap">${flower()}<h2>Det där räknas också<br>som väl använd tid.</h2><a href="/" class="text-link">Tillbaka till Omar ${icon('arrow')}</a></section>`;
}
export function about(page) {
  return `<div class="section-wrap">${breadcrumb(page)}<section class="about-hero"><div><p class="eyebrow">HEJ. JAG ÄR OMAR.</p><h1>Teknik är kul.<br><span>Människor också.</span></h1><p class="large-lead">Maskiningenjör. Nyfiken på kod.<br>Inte särskilt bra på att sluta undra.</p></div><div class="about-flower">${flower()}<span>100% MÄNNISKA<br>ÄVEN VID OMSTART.</span></div></section><section class="about-body" aria-labelledby="about-heading"><div class="about-side"><span class="eyebrow">MELLAN SKRUV OCH KOD</span><p>”Men tänk om<br>man gjorde så här?”</p><span>Ofta början på något.</span></div><div><h2 id="about-heading">Det ska fungera.<br>Och kännas genomtänkt.</h2><p>Jag heter Omar Yusuf. Jag gillar att förstå hur saker hänger ihop, plocka isär en idé och sätta ihop den lite bättre.</p><p>Maskinteknik är min grund. Kod är ett annat sätt att bygga. Jag utforskar gärna mötet mellan automation, mekatronik och digitala verktyg.</p><p>Det är därför den här sidan har både ett projekt om AI-verktyg och en maskin som skriver ut små vinster. Allt behöver inte göra samma sak. Men det ska vara gjort med omtanke.</p><div class="interest-tags"><span>Maskinteknik</span><span>Automation</span><span>Mekatronik</span><span>Kod</span><span>R&B, soul & jazz</span></div><p class="about-footnote">Mer om vad jag arbetar med finns på <a href="${site.github}" rel="me">min offentliga GitHub-profil</a>.</p></div></section>${experience()}<section class="principles" aria-label="Det jag gillar att bygga med"><div><span>01</span><h3>Nyfikenhet.</h3><p>En bra fråga är oftast mer intressant än ett snabbt svar.</p></div><div><span>02</span><h3>Omtanke.</h3><p>Detaljer märks. Även de som ingen uttryckligen bad om.</p></div><div><span>03</span><h3>Lite bus.</h3><p>Seriöst arbete behöver inte ha ett allvarligt ansiktsuttryck.</p></div></section><section class="about-cta"><h2>Ska vi testa<br>en idé?</h2><a href="/kontakt/" class="button button-ink">Säg hej ${icon('diagonal')}</a></section></div>`;
}
export function furl(page) {
  return `<div class="section-wrap">${breadcrumb(page)}<section class="project-hero"><div><p class="eyebrow">FURL / ÖPPEN KÄLLKOD</p><h1>Mindre brus.<br><span>Mer sammanhang.</span></h1><p class="large-lead">Furl packar ihop stora verktygssvar för AI-agenter. Det som viks undan går att hämta igen.</p><a class="button button-ink" href="${site.furl}">Se Furl på GitHub ${icon('diagonal')}</a></div><div class="project-hero-art" aria-hidden="true"><div class="furl-folds"><i></i><i></i><i></i><i></i><i></i><i></i></div><span>ROLL IT UP.<br>KEEP IT ALL.</span></div></section><section class="project-story" aria-labelledby="furl-story-title"><div><p class="eyebrow">VAD DET ÄR</p><h2 id="furl-story-title">Allt behöver inte ligga<br>på skrivbordet samtidigt.</h2></div><div><p>En AI-agent kan få väldigt mycket text tillbaka från sina verktyg: loggar, sökresultat och stora datasvar. Allt behöver inte vara synligt samtidigt för nästa steg.</p><p>Furl skapar en kompakt vy och behåller originalinnehållet för senare hämtning. Agenten behöver själv begära sådant som inte längre syns. Tillgänglig data är inte samma sak som att allt syns automatiskt.</p><p>Projektet erbjuder verktyg via MCP och går också att använda som ett Python-bibliotek. Exakt stöd, begränsningar och aktuella mätningar finns i projektets dokumentation.</p></div></section><section class="compression-demo" aria-labelledby="demo-title"><div class="demo-heading"><div><p class="eyebrow">EN FÖRENKLAD ILLUSTRATION</p><h2 id="demo-title">Vik ihop. Vik ut.</h2></div><button class="button button-outline js-only" data-fold aria-pressed="false" hidden>Vik ihop ${icon('arrow')}</button></div><div class="demo-lines" data-demo-lines><span>verktyg: nästa steg är redo</span><span class="repeat-line">status: allt är oförändrat</span><span class="repeat-line">status: allt är oförändrat</span><span class="repeat-line">status: allt är oförändrat</span><span class="folded-line" hidden>↳ 3 likadana statusrader, finns kvar att visa</span><span>resultat: det här behöver du se</span></div><p class="demo-caption" role="status" data-fold-status>Alla rader visas. Detta är en illustration, inte en körning av Furl eller ett prestandatest.</p></section><section class="project-outro"><h2>Nyfiken på detaljerna?</h2><p>Kod, installation och öppna frågor finns i repot.</p><div class="project-links"><a href="${site.furl}" class="button button-ink">Öppna projektet ${icon('diagonal')}</a><a href="${site.furl}/issues" class="text-link">Frågor och förbättringar ${icon('diagonal')}</a></div><a href="/#byggen" class="text-link back-to-work">Tillbaka till byggena ${icon('arrow')}</a></section></div>`;
}
export function contact(page) {
  return `<div class="section-wrap">${breadcrumb(page)}<section class="contact-hero"><p class="eyebrow">INGEN PITCHDECK KRÄVS</p><h1>Det börjar<br>med <span>hej.</span></h1><p class="large-lead">En idé du vill bolla? En fråga om något jag bygger?<br>Eller bara en riktigt bra ordvits?</p>${postalForm()}<div class="contact-options"><a href="${site.github}" class="contact-option"><div>${icon('github')}<span class="eyebrow">DEN OFFENTLIGA VÄGEN IN</span></div><h2>Hitta mig<br>på GitHub.</h2><p>Mina projekt och de kontaktvägar jag delar där.</p><span class="contact-option-link">Öppna min profil ${icon('diagonal')}</span></a><a href="${site.furl}/issues" class="contact-option contact-option--paper"><div>${icon('smile')}<span class="eyebrow">EN FRÅGA OM FURL?</span></div><h2>Låt oss göra<br>det bättre.</h2><p>Rapportera ett problem eller föreslå en förbättring.</p><span class="contact-option-link">Till Furls ärenden ${icon('diagonal')}</span></a></div><p class="contact-disclosure">GitHub-länkarna tar dig till en annan webbplats. Ärenden i det offentliga Furl-repot är synliga för andra. Dela inte lösenord eller privata uppgifter där.</p><div class="contact-postscript">${flower()}<p>Ett hej räcker långt.<br>Resten kan vi lista ut tillsammans.</p></div></section></div>`;
}
export function notFound(page) {
  return `<section class="not-found section-wrap"><div class="error-art" aria-hidden="true"><span>4</span>${flower()}<span>4</span></div><p class="eyebrow">LITET TEKNISKT FIKABREAK</p><h1>Den här sidan<br>tog fikapaus.</h1><p>Länken kanske är gammal. Eller så blev det ett litet skrivfel.<br>Du är hur som helst fortfarande välkommen.</p><div class="error-actions"><a href="/" class="button button-ink">Till startsidan ${icon('arrow')}</a><a href="/verkstad/" class="button button-outline">Ta en roligare omväg ${icon('smile')}</a></div><span class="error-note">HTTP 404. Humöret behöver inte följa med.</span></section>`;
}
