import { $, escape, field, dateLabel } from './dom.mjs';
import { filterWins, WIN_BATCH_ACTIONS } from './win-bulk.mjs';
export { defaultWinDesign } from '../../content/win-design.mjs';

export const flavors = { kind: 'Pepp', joke: 'Humor', pause: 'Paus', roast: 'Gliringar' };

export function pageList(pages, selected, query = '') {
  const filtered = pages.filter(page => `${page.name} ${page.path}`.toLowerCase().includes(query.toLowerCase()));
  const main = filtered.filter(page => !['privacy', 'cookies', 'terms', 'accessibility', 'notFound'].includes(page.template));
  const legal = filtered.filter(page => !main.includes(page));
  const row = page => `<button type="button" class="page-row ${page.id === selected ? 'is-selected' : ''}" data-page-id="${escape(page.id)}"><span class="page-symbol" aria-hidden="true">${page.path === '/' ? '⌂' : '▱'}</span><span class="page-name">${escape(page.name)}</span>${page.id === selected ? '<span class="row-dot" aria-hidden="true"></span>' : ''}</button>`;
  $('#library-list').innerHTML = `${main.map(row).join('')}${legal.length ? '<div class="library-group">DET FINSTILTA</div>' + legal.map(row).join('') : ''}${filtered.length ? '' : '<p class="inspector-help" style="padding:12px">Ingen sida matchar sökningen.</p>'}`;
}

export function assetNavigation(mode, assets, cards, mediaTotal = null) {
  const uploads = mediaTotal ?? assets.filter(asset => !asset.builtin && (asset.state ?? (asset.archived ? 'archived' : 'active')) === 'active').length;
  $('#library-list').innerHTML = `<button type="button" class="asset-nav-row ${mode === 'media' || mode === 'asset' ? 'is-selected' : ''}" data-special="media"><span class="page-symbol">▧</span> Bilder & typsnitt <small style="margin-left:auto">${uploads}</small></button><button type="button" class="asset-nav-row ${mode === 'wins' || mode === 'win' ? 'is-selected' : ''}" data-special="wins"><span class="page-symbol">✳</span> Små vinster <small style="margin-left:auto">${cards.filter(card => (card.state ?? 'active') === 'active').length}</small></button><div class="library-group">VERKSTADENS INNEHÅLL</div><p class="inspector-help" style="padding:0 12px">Bilder, bokstäver och små saker värda att le åt.</p>`;
}

export function mediaGallery(assets, query = '', state = 'active') {
  const visible = assets.filter(asset => (asset.state ?? (asset.archived ? 'archived' : 'active')) === state && `${asset.name} ${asset.mime}`.toLowerCase().includes(query.toLowerCase()));
  const labels = { active: 'Aktiva', archived: 'Arkiverade', trash: 'Papperskorg' };
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">DINA BYGGBITAR</p><h1>Resursrummet<span style="color:#234ce7">.</span></h1><p>Bilder, typsnitt och redigerbara resurser som ger webbplatsen personlighet.</p></div><button type="button" class="small-button primary" data-action="upload">＋ Ladda upp</button></div><div class="asset-filters lifecycle-tabs">${Object.entries(labels).map(([key,label])=>`<button type="button" data-media-state="${key}" class="${state===key?'is-selected':''}">${label}</button>`).join('')}<span class="inspector-help">${visible.length} ${labels[state].toLowerCase()}</span></div><div class="asset-grid">${visible.map(asset => `<button type="button" class="asset-card" data-asset-id="${escape(asset.id)}"><div class="asset-image">${asset.mime.startsWith('image/') || asset.mime === 'image/svg+xml' ? `<img src="${escape(asset.src)}" alt="${escape(asset.alt ?? '')}" loading="lazy">` : '<span class="font-preview" aria-hidden="true">Aa</span>'}</div><div class="asset-card-meta"><strong>${escape(asset.name)}</strong><small>${asset.width ? `${asset.width} × ${asset.height} · ` : ''}${escape(asset.mime.split('/').at(-1).toUpperCase())}${asset.builtin ? ' · Original' : ''}</small></div></button>`).join('')}</div>${visible.length ? '' : `<div class="empty-state"><h2>${state === 'trash' ? 'Papperskorgen är tom.' : 'Ingen resurs här.'}</h2><p>${state === 'active' ? 'Ladda upp en bild eller ett eget WOFF2-typsnitt.' : 'Byt flik eller återställ en resurs.'}</p></div>`}`;
}

export function winGallery(cards, flavor = 'all', query = '', limit = 60, { state = 'active', selected = new Set() } = {}) {
  const visible = filterWins(cards, { state, flavor, query });
  const shown = visible.slice(0, limit);
  const stateLabels = { active: 'Aktiva', archived: 'Arkiverade', trash: 'Papperskorg' };
  const batchActions = Object.entries(WIN_BATCH_ACTIONS).map(([id,action]) => id === 'category' ? `<select id="batch-win-category" aria-label="Ny kategori">${Object.entries(flavors).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select><button type="button" class="small-button" data-action="batch-${id}-wins">${action.label}</button>` : `<button type="button" class="small-button ${action.tone === 'danger' ? 'danger' : ''}" data-action="batch-${id}-wins">${action.label}</button>`).join('');
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">FRÅN GLÄDJEVERKET</p><h1>Små vinster<span style="color:#234ce7">.</span></h1><p>Markera många, gör en ändring en gång och behåll stabila länkar.</p></div><div class="bulk-heading-actions"><button type="button" class="small-button" data-action="import-wins">Importera JSON</button><button type="button" class="small-button primary" data-action="new-win">＋ Ny vinst</button></div></div><div class="asset-filters lifecycle-tabs">${Object.entries(stateLabels).map(([key,label])=>`<button type="button" data-win-state="${key}" class="${state===key?'is-selected':''}">${label}</button>`).join('')}</div><div class="asset-filters">${Object.entries({ all: 'Alla', ...flavors }).map(([key, name]) => `<button type="button" data-win-filter="${key}" class="${flavor === key ? 'is-selected' : ''}">${name}</button>`).join('')}<input type="search" id="win-search" aria-label="Sök vinster" placeholder="Hitta en liten vinst…" value="${escape(query)}"></div><div class="win-selection-bar"><strong>${selected.size} valda</strong><button type="button" class="small-button" data-action="select-visible-wins">Markera visade</button><button type="button" class="small-button" data-action="select-matching-wins">Markera alla träffar</button><button type="button" class="small-button" data-action="clear-win-selection">Rensa</button>${selected.size ? batchActions : ''}</div><div class="win-grid">${shown.map(card => `<article class="win-card-wrap ${selected.has(card.id)?'is-selected':''}"><label class="win-select"><input type="checkbox" data-win-select="${escape(card.id)}" ${selected.has(card.id)?'checked':''}><span>Markera</span></label><button type="button" class="win-card ${card.flavor}" data-win-id="${escape(card.id)}"><span>${flavors[card.flavor]}</span><strong>${escape(card.text)}</strong><small>${escape(card.id)} ↗</small></button></article>`).join('')}</div>${visible.length > limit ? `<button type="button" class="small-button" data-action="more-wins" style="margin-top:24px">Visa fler · ${visible.length - limit} kvar</button>` : ''}${visible.length ? '' : '<div class="empty-state"><h2>Ingen träff den här gången.</h2><p>Prova en annan sökning eller status.</p></div>'}`;
}

export function winFields(card) {
  return `<section class="inspector-section"><h2>Vinstens innehåll</h2>${field('Text på vinsten', 'win-text', card.text, { textarea: true })}<label class="inspector-field">Kategori<select id="win-flavor">${Object.entries(flavors).map(([value, name]) => `<option value="${value}" ${value === card.flavor ? 'selected' : ''}>${name}</option>`).join('')}</select></label>${field('Stabil identitet', 'win-id', card.id, { readonly: true })}<button type="button" class="small-button" data-action="export-win">Spara förhandsbild ↗</button><p class="inspector-help">Samma design visas i maskinen och följer med bilden som besökaren sparar.</p></section>`;
}

export function assetDetail(asset, usage = { currentReferences: null, historyReferences: null }) {
  const state = asset.state ?? (asset.archived ? 'archived' : 'active');
  const count = value => value === null ? '…' : String(value);
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">EN DEL AV WEBBPLATSEN</p><h1>${escape(asset.name)}</h1><p>${asset.width ? `${asset.width} × ${asset.height} px · ` : ''}${escape(asset.mime)} · ${state === 'active' ? 'Aktiv' : state === 'archived' ? 'Arkiverad' : 'Papperskorg'}</p></div><button type="button" class="small-button" data-special="media">Till biblioteket</button></div><div class="asset-image" style="height:360px;border:1px solid #dce3ce;border-radius:8px">${asset.mime.startsWith('image/') ? `<img src="${escape(asset.src)}" alt="${escape(asset.alt ?? '')}" style="padding:30px">` : '<span class="font-preview">Aa Bb Cc</span>'}</div><p id="asset-usage" class="inspector-help" style="margin-top:20px">${count(usage.currentReferences)} referenser i aktuellt utkast · ${count(usage.historyReferences)} i sparad historik.</p>`;
  const lifecycle = state === 'active' ? '<button type="button" class="small-button" data-action="archive-asset">Arkivera</button><button type="button" class="small-button danger" data-action="trash-asset">Flytta till papperskorg</button>' : state === 'archived' ? '<button type="button" class="small-button" data-action="restore-asset">Återställ</button><button type="button" class="small-button danger" data-action="trash-asset">Flytta till papperskorg</button>' : '<button type="button" class="small-button" data-action="restore-asset">Återställ</button><button type="button" class="small-button danger" data-action="delete-asset">Radera permanent</button>';
  $('#custom-inspector').innerHTML = `<section class="inspector-section"><h2>Filens uppgifter</h2>${field('Namn', 'asset-name', asset.name)}${field('Alternativtext', 'asset-alt', asset.alt ?? '', { textarea: true })}<div class="inspector-actions"><button type="button" class="small-button primary" data-action="save-asset">Spara metadata</button><button type="button" class="small-button" data-action="replace-asset">Ersätt fil</button>${asset.editableSrc ? '<button type="button" class="small-button primary" data-action="edit-svg-asset">Redigera SVG</button>' : ''}${lifecycle}</div><p class="inspector-help">${asset.builtin ? 'Originalet ligger kvar i källkoden; CMS-status och metadata sparas separat.' : 'Publicerade/historiska bytes bevaras tills permanent radering är säker.'}</p></section>`;
}

export function historyView(history, currentVersion) {
  const items = [...history.items, ...(history.next ? [] : [{ version: 0, summary: 'Webbplatsens ursprungliga form och innehåll.', createdAt: null }])];
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">INGET BRA BEHÖVER GÅ FÖRLORAT</p><h1>Bakåt är också framåt<span style="color:#234ce7">.</span></h1><p>Granska en version. Återställ till utkast. Spara när det känns rätt.</p></div></div>${items.length ? `<div class="history-list">${items.map(item => `<article class="history-row"><span class="history-version">${item.version}</span><div><h2>${item.version === 0 ? 'Originalet' : item.version === currentVersion ? 'Publicerad just nu' : `Version ${item.version}`}</h2><p>${escape(item.summary)}</p>${item.createdAt ? `<time datetime="${escape(item.createdAt)}">${dateLabel(item.createdAt)}</time>` : '<span class="inspector-help">Alltid möjlig att återställa.</span>'}</div><div class="history-actions"><button type="button" class="small-button" data-review-version="${item.version}">Granska</button><button type="button" class="small-button" data-restore-version="${item.version}">Återställ</button></div></article>`).join('')}</div>${history.next ? `<button type="button" class="small-button" data-more-history="${history.next}" style="margin-top:20px">Visa äldre versioner</button>` : ''}` : '<div class="empty-state"><h2>Första kapitlet är oskrivet.</h2><p>Spara en ändring så börjar historiken här.</p></div>'}`;
}
