import { $, escape, field, dateLabel } from './dom.mjs';
export { defaultWinDesign } from '../../content/win-design.mjs';

export const flavors = { kind: 'Pepp', joke: 'Humor', pause: 'Paus', roast: 'Gliringar' };

export function pageList(pages, selected, query = '') {
  const filtered = pages.filter(page => `${page.name} ${page.path}`.toLowerCase().includes(query.toLowerCase()));
  const main = filtered.filter(page => !['privacy', 'cookies', 'terms', 'accessibility', 'notFound'].includes(page.template));
  const legal = filtered.filter(page => !main.includes(page));
  const row = page => `<button type="button" class="page-row ${page.id === selected ? 'is-selected' : ''}" data-page-id="${escape(page.id)}"><span class="page-symbol" aria-hidden="true">${page.path === '/' ? '⌂' : '▱'}</span><span class="page-name">${escape(page.name)}</span>${page.id === selected ? '<span class="row-dot" aria-hidden="true"></span>' : ''}</button>`;
  $('#library-list').innerHTML = `${main.map(row).join('')}${legal.length ? '<div class="library-group">DET FINSTILTA</div>' + legal.map(row).join('') : ''}${filtered.length ? '' : '<p class="inspector-help" style="padding:12px">Ingen sida matchar sökningen.</p>'}`;
}

export function assetNavigation(mode, assets, cards) {
  $('#library-list').innerHTML = `<button type="button" class="asset-nav-row ${mode === 'media' || mode === 'asset' ? 'is-selected' : ''}" data-special="media"><span class="page-symbol">▧</span> Bilder & typsnitt <small style="margin-left:auto">${assets.filter(asset => !asset.archived).length}</small></button><button type="button" class="asset-nav-row ${mode === 'wins' || mode === 'win' ? 'is-selected' : ''}" data-special="wins"><span class="page-symbol">✳</span> Små vinster <small style="margin-left:auto">${cards.length}</small></button><div class="library-group">VERKSTADENS INNEHÅLL</div><p class="inspector-help" style="padding:0 12px">Bilder, bokstäver och små saker värda att le åt.</p>`;
}

export function mediaGallery(assets, query = '', archived = false) {
  const visible = assets.filter(asset => Boolean(asset.archived) === archived && `${asset.name} ${asset.mime}`.toLowerCase().includes(query.toLowerCase()));
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">DINA BYGGBITAR</p><h1>Resursrummet<span style="color:#234ce7">.</span></h1><p>Bilder och typsnitt som ger webbplatsen personlighet.</p></div><button type="button" class="small-button primary" data-action="upload">＋ Ladda upp</button></div><div class="asset-filters"><button type="button" data-action="toggle-archived">${archived ? '← Till aktiva filer' : 'Visa arkiverade'}</button><span class="inspector-help">${archived ? 'Arkiverade filer kan återföras till biblioteket.' : 'Aktiva filer'}</span></div><div class="asset-grid">${visible.map(asset => `<button type="button" class="asset-card" data-asset-id="${escape(asset.id)}"><div class="asset-image">${asset.mime.startsWith('image/') ? `<img src="${escape(asset.src)}" alt="${escape(asset.alt ?? '')}" loading="lazy">` : '<span class="font-preview" aria-hidden="true">Aa</span>'}</div><div class="asset-card-meta"><strong>${escape(asset.name)}</strong><small>${asset.width ? `${asset.width} × ${asset.height} · ` : ''}${escape(asset.mime.split('/').at(-1).toUpperCase())}${asset.builtin ? ' · Original' : ''}</small></div></button>`).join('')}</div>${visible.length ? '' : '<div class="empty-state"><h2>Plats för något nytt.</h2><p>Ladda upp en bild eller ett eget WOFF2-typsnitt.</p></div>'}`;
}

export function winGallery(cards, flavor = 'all', query = '', limit = 60) {
  const visible = cards.filter(card => (flavor === 'all' || card.flavor === flavor) && `${card.id} ${card.text}`.toLowerCase().includes(query.toLowerCase()));
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">FRÅN GLÄDJEVERKET</p><h1>Små vinster<span style="color:#234ce7">.</span></h1><p>Redigera orden. Forma känslan. Behåll länken.</p></div><button type="button" class="small-button primary" data-action="new-win">＋ Ny vinst</button></div><div class="asset-filters">${Object.entries({ all: 'Alla', ...flavors }).map(([key, name]) => `<button type="button" data-win-filter="${key}" class="${flavor === key ? 'is-selected' : ''}">${name}</button>`).join('')}<input type="search" id="win-search" aria-label="Sök vinster" placeholder="Hitta en liten vinst…" value="${escape(query)}"></div><div class="win-grid">${visible.slice(0, limit).map(card => `<button type="button" class="win-card ${card.flavor}" data-win-id="${escape(card.id)}"><span>${flavors[card.flavor]}</span><strong>${escape(card.text)}</strong><small>${escape(card.id)} ↗</small></button>`).join('')}</div>${visible.length > limit ? `<button type="button" class="small-button" data-action="more-wins" style="margin-top:24px">Visa fler · ${visible.length - limit} kvar</button>` : ''}${visible.length ? '' : '<div class="empty-state"><h2>Ingen träff den här gången.</h2><p>Prova en annan sökning.</p></div>'}`;
}

export function winFields(card) {
  return `<section class="inspector-section"><h2>Vinstens innehåll</h2>${field('Text på vinsten', 'win-text', card.text, { textarea: true })}<label class="inspector-field">Kategori<select id="win-flavor">${Object.entries(flavors).map(([value, name]) => `<option value="${value}" ${value === card.flavor ? 'selected' : ''}>${name}</option>`).join('')}</select></label>${field('Stabil identitet', 'win-id', card.id, { readonly: true })}<button type="button" class="small-button" data-action="export-win">Spara förhandsbild ↗</button><p class="inspector-help">Samma design visas i maskinen och följer med bilden som besökaren sparar.</p></section>`;
}

export function assetDetail(asset, usage = 0) {
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">EN DEL AV WEBBPLATSEN</p><h1>${escape(asset.name)}</h1><p>${asset.width ? `${asset.width} × ${asset.height} px · ` : ''}${escape(asset.mime)}</p></div><button type="button" class="small-button" data-special="media">Till biblioteket</button></div><div class="asset-image" style="height:360px;border:1px solid #dce3ce;border-radius:8px">${asset.mime.startsWith('image/') ? `<img src="${escape(asset.src)}" alt="${escape(asset.alt ?? '')}" style="padding:30px">` : '<span class="font-preview">Aa Bb Cc</span>'}</div><p class="inspector-help" style="margin-top:20px">${usage} referenser i aktuellt utkast. Äldre versioners filer bevaras.</p>`;
  $('#custom-inspector').innerHTML = `<section class="inspector-section"><h2>Filens uppgifter</h2>${field('Namn', 'asset-name', asset.name, { readonly: asset.builtin })}${field('Alternativtext', 'asset-alt', asset.alt ?? '', { textarea: true, readonly: asset.builtin })}<div class="inspector-actions">${asset.builtin ? '' : '<button type="button" class="small-button primary" data-action="save-asset">Spara uppgifter</button>'}<button type="button" class="small-button" data-action="replace-asset">Ersätt fil</button>${asset.builtin ? '' : asset.archived ? '<button type="button" class="small-button" data-action="unarchive-asset">Återför till biblioteket</button>' : '<button type="button" class="small-button danger" data-action="archive-asset">Arkivera</button>'}</div><p class="inspector-help">${asset.builtin ? 'Originalfilen ingår i webbplatsens källkod. Ersätt den för att uppdatera dess användningar genom CMS.' : 'Alternativtexten används när filen läggs in. En bilds befintliga alternativtext redigeras direkt på sidan.'}</p></section>`;
}

export function historyView(history, currentVersion) {
  const items = [...history.items, ...(history.next ? [] : [{ version: 0, summary: 'Webbplatsens ursprungliga form och innehåll.', createdAt: null }])];
  $('#special-stage').innerHTML = `<div class="special-heading"><div><p class="special-kicker">INGET BRA BEHÖVER GÅ FÖRLORAT</p><h1>Bakåt är också framåt<span style="color:#234ce7">.</span></h1><p>Granska en version. Återställ till utkast. Spara när det känns rätt.</p></div></div>${items.length ? `<div class="history-list">${items.map(item => `<article class="history-row"><span class="history-version">${item.version}</span><div><h2>${item.version === 0 ? 'Originalet' : item.version === currentVersion ? 'Publicerad just nu' : `Version ${item.version}`}</h2><p>${escape(item.summary)}</p>${item.createdAt ? `<time datetime="${escape(item.createdAt)}">${dateLabel(item.createdAt)}</time>` : '<span class="inspector-help">Alltid möjlig att återställa.</span>'}</div><div class="history-actions"><button type="button" class="small-button" data-review-version="${item.version}">Granska</button><button type="button" class="small-button" data-restore-version="${item.version}">Återställ</button></div></article>`).join('')}</div>${history.next ? `<button type="button" class="small-button" data-more-history="${history.next}" style="margin-top:20px">Visa äldre versioner</button>` : ''}` : '<div class="empty-state"><h2>Första kapitlet är oskrivet.</h2><p>Spara en ändring så börjar historiken här.</p></div>'}`;
}
